- name: Deploy TG Bot
  hosts: TG_Bot
  become: yes
  vars:
    tg_bot_repo: "https://github.com/NopiumE/devops.git"
    repo_dir: "/tg_bot"
    tg_bot_dir: "{{ repo_dir }}/bot"
  tasks:
    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Clone TG bot repository
      git:
        repo: "{{ tg_bot_repo }}"
        dest: "{{ repo_dir }}"
        version: devops

    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: "{{ tg_bot_dir }}/requirements.txt"

    - name: Create .env file with variables from inventory
      copy:
        dest: "{{ tg_bot_dir }}/.env"
        content: |
          TOKEN={{ hostvars[inventory_hostname]['TOKEN'] }}
          DB_HOST={{ hostvars[inventory_hostname]['DB_HOST'] }}
          DB_PORT={{ hostvars[inventory_hostname]['DB_PORT'] }}
          DB_USER={{ hostvars[inventory_hostname]['DB_USER'] }}
          DB_PASSWORD={{ hostvars[inventory_hostname]['DB_PASSWORD'] }}
          DB_DATABASE={{ hostvars[inventory_hostname]['DB_DATABASE'] }}
          RM_HOST={{ hostvars[inventory_hostname]['RM_HOST'] }}
          RM_PORT={{ hostvars[inventory_hostname]['RM_PORT'] }}
          RM_USER={{ hostvars[inventory_hostname]['RM_USER'] }}
          RM_PASSWORD={{ hostvars[inventory_hostname]['RM_PASSWORD'] }}

    - name: Create systemd service file for TG bot
      copy:
        dest: /etc/systemd/system/tg_bot.service
        content: |
          [Unit]
          Description=TG Bot
          After=network.target

          [Service]
          User=root
          WorkingDirectory={{ tg_bot_dir }}
          EnvironmentFile={{ tg_bot_dir }}/.env
          ExecStart=/usr/bin/python3 {{ tg_bot_dir }}/bot.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable TG bot service
      systemd:
        name: tg_bot
        state: started
        enabled: yes

- name: TASKS FOR DB_Servers
  hosts: db_servers
  become: yes
  tasks:
    - name: apt update&upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 120000

    - name: Adding apt repository key of PostgreSQL
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: Adding apt repository of PostgreSQL
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main"
        state: present
        filename: "PostgreSQL_repo"

    - name: Install packages for PostgreSQL
      apt:
        name:
          - postgresql-15
          - postgresql-contrib
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
    
    - name: Install psycopg2-binary
      pip:
        name: psycopg2-binary
        state: present

    - name: Is PostgreSQL installed?
      command: "psql --version"
      ignore_errors: yes
      register: psql_version

    - name: Fail if PostgreSQL is not installed
      fail:
        msg: "PostgreSQL has not been installed"
      when: psql_version.failed

    - name: Get PostgreSQL cluster status
      command: pg_ctlcluster 15 main status
      ignore_errors: yes
      register: postgres_status

    - name: If PostgreSQL cluster isn't running then start it
      command: pg_ctlcluster 15 main start
      when: postgres_status is defined and postgres_status.stdout.find('is not running') != -1

- name: Main DB_Server Configuration
  hosts: DB
  become: yes
  tasks:

    - name: Create archive directory for PostgreSQL
      file:
        path: /oracle/pg_data/archive/
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'
        recurse: yes
        
    - name: pg_hba.conf Configuration
      blockinfile:
        create: true
        path: /etc/postgresql/15/main/pg_hba.conf
        block: |
          local all {{ hostvars[inventory_hostname]['DB_USER'] }} peer
          host all all "{{ hostvars[inventory_hostname]['DB_HOST'] }}"/24 trust
          host replication {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} {{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}/24 trust

    - name: postgresql.conf Configuration
      blockinfile:
        create: true
        path: /etc/postgresql/15/main/postgresql.conf
        block: | 
          listen_addresses = '*'
          port = 5432
          log_destination = 'stderr'
          logging_collector = on
          log_directory = '/var/log/postgresql/'
          log_filename = 'postgresql.log'
          log_file_mode = 0644
          archive_mode = on
          archive_command = 'cp %p /oracle/pg_data/archive/%f'
          max_wal_senders = 10
          wal_level = replica
          wal_log_hints = on
          log_replication_commands = on

    - name: Restart PostgreSQL service
      service:
        name: postgresql
        state: restarted

    - name: Database creation
      community.general.postgresql_db:
        name: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
        encoding: UTF-8
        template: template0
      become: yes
      become_user: postgres

    - name: Create tables for emails and phone numbers
      shell: |
        psql -d {{ hostvars[inventory_hostname]['DB_DATABASE'] }} -c "CREATE TABLE IF NOT EXISTS emails (id serial PRIMARY KEY, email text);"
        psql -d {{ hostvars[inventory_hostname]['DB_DATABASE'] }} -c "CREATE TABLE IF NOT EXISTS numbers (id serial PRIMARY KEY, phone_number text);"
      become_user: postgres
      ignore_errors: true

    - name: Change password for postgres user
      command: psql -c "ALTER USER {{ hostvars[inventory_hostname]['DB_USER'] }} WITH PASSWORD '{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}';"
      become_user: postgres

    - name: Create user for replication
      command: psql -c "DO $$ BEGIN CREATE ROLE {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} REPLICATION LOGIN SUPERUSER PASSWORD '{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;"
      become_user: postgres

- name: Replication Server Configuration
  hosts: DB_repl
  become: yes
  tasks:
    - name: Is PostgreSQL running?
      ansible.builtin.command:
        cmd: "pg_ctlcluster 15 main status"
      register: postgres_status
      ignore_errors: true
      become: yes
      become_user: root

    - name: If PostgreSQL cluster doesn't exist then create it
      ansible.builtin.command:
        cmd: "pg_createcluster 15 main"
      when: postgres_status.stdout.find('specified cluster \'15 main\' does not exist') != -1
      become: yes
      become_user: root

    - name: Setup postgresql.conf
      blockinfile:
        create: true
        path: /etc/postgresql/15/main/postgresql.conf
        block: |
          listen_addresses = 'localhost, {{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}'
          port = {{ hostvars[inventory_hostname]['DB_REPL_PORT'] }}

    - name: Stop PostgreSQL service before backup
      service:
        name: postgresql
        state: stopped

    - name: Clean up old data before backup
      command: rm -rf /var/lib/postgresql/15/main/*
      become_user: root

    - name: Ensure directory is clean before backup
      command: find /var/lib/postgresql/15/main/ -mindepth 1 -delete
      become: true

    - name: Perform pg_basebackup 
      command: pg_basebackup -R -h {{ hostvars[inventory_hostname]['DB_HOST'] }} -U {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} -D /var/lib/postgresql/15/main -P 
      become_user: postgres
      environment:
        PGPASSWORD: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"

    - name: Set permissions for the replication directory
      file:
        path: /var/lib/postgresql/15/main/
        owner: postgres
        group: postgres
        recurse: yes
      become: true

    - name: Ensure proper ownership for PostgreSQL directory
      command: chown -R postgres:postgres /var/lib/postgresql/
      become: true

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
